(()=>{'use strict';
const T=Training,key='hansol-training-v2',app=document.querySelector('#app'),admin=document.body.dataset.educationRole==='admin',id=new URLSearchParams(location.search).get('id')||'demo-01';
let state,tab=['templates','peak'].includes(new URLSearchParams(location.search).get('tab'))?new URLSearchParams(location.search).get('tab'):'people',screen='video',answers=Array(10).fill(null),questionIndex=0,timer=null,query='',filter='',sort='name',page=1,pageSize=25,expandedId=null,editing=null,dirty=false,uploading=false,objectURLs=[],epoch=0,peakTotal=120,peakComplete=90;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
function read(){const raw=localStorage.getItem(key);if(!raw)return null;const data=JSON.parse(raw);for(const p of data.people||[]){if(p.company==='가상 한솔설비')p.company='가상 A설비'}return data}
try{state=read();if(!state){const old=JSON.parse(localStorage.getItem('hansol-video-demo-v1'));state=T.seed(Array.isArray(old)?old:null);localStorage.setItem(key,JSON.stringify(state))}}catch{app.innerHTML='<h1>브라우저 저장소를 사용할 수 없습니다.</h1><p>저장 기능을 허용한 브라우저에서 다시 열어주세요.</p>';return}
document.body.classList.toggle('admin',admin);document.body.classList.toggle('visitor',!admin);document.querySelector('#role').textContent=admin?'관리자용':'방문자용';document.title=(admin?'사전 안전교육 관리':'방문자 사전 안전교육')+' | PreCheck · 한솔홀딩스';
const person=()=>state.people.find(p=>p.id===id);
const template=id=>state.templates.find(t=>t.id===id);
const course=p=>template(p.courseId)?.versions.find(v=>v.revision===p.revision);
const stamp=p=>p.courseId+':'+p.revision;
function notice(text,error=false){const el=document.querySelector('#message');if(el){el.textContent=text;el.className=error?'error':'saved'}}
function change(fn){const latest=read()||state;fn(latest);localStorage.setItem(key,JSON.stringify(latest));state=latest;}
function attempt(fn){try{fn()}catch(e){notice(e.message,true)}}
function patchPerson(expected,fn){change(s=>{const p=s.people.find(x=>x.id===id);if(!p||stamp(p)!==expected)throw Error('배정된 교육이 변경되었습니다. 새로고침 후 시작해주세요.');fn(p)})}
function options(selected){return state.templates.flatMap(t=>t.versions.map(v=>`<option value="${esc(t.id)}:${v.revision}" ${selected===t.id+':'+v.revision?'selected':''}>${esc(v.title)} · v${v.revision}</option>`)).join('')}
function url(p){const u=new URL('education-worker.html',location.href);u.searchParams.set('id',p.id);return u.href}
function badge(p){return `<span class="badge ${T.complete(p)?'m_success':p.score!==null&&p.score<8?'m_warning':''}">${T.status(p)}</span>`}
function stop(){clearInterval(timer);timer=null;document.querySelector('#actualVideo')?.pause();const b=document.querySelector('#play');if(b)b.textContent='▶ 재생'}
function cleanup(){stop();epoch++;objectURLs.forEach(u=>URL.revokeObjectURL(u));objectURLs=[]}
function render(){cleanup();if(admin){renderAdmin();return}const p=person(),c=p&&course(p);if(!p||!c){app.innerHTML='<h1>교육 링크를 확인해주세요</h1><p>등록된 개인과 배정 교육을 찾을 수 없습니다. 안내 담당자에게 문의해주세요.</p>';return}
app.innerHTML=`<div class="visitor-identity"><span class="avatar" aria-hidden="true">${esc(p.name.slice(0,1))}</span><div><strong>${esc(p.name)}님</strong><small>${esc(p.company)}</small></div><span class="badge">사전교육</span></div><h1>${screen==='quiz'?'안전수칙을 확인해요':screen==='result'?'교육 결과 확인':'영상으로 준비하는 안전'}</h1><div class="course-label"><strong>${esc(c.title)}</strong> · v${c.revision}</div><ol class="steps" aria-label="교육 진행 단계"><li class="active"><b>1</b> 영상 시청</li><li class="${T.watched(p)?'active':''}"><b>2</b> 문제풀이</li><li class="${T.complete(p)?'active':''}"><b>3</b> 완료</li></ol><div id="message" role="status" aria-live="polite"></div><div id="stage"></div>`;
if(screen==='quiz'&&T.watched(p))quiz();else if(screen==='result'&&p.score!==null)result();else video()}
function video(){const p=person(),c=course(p),demo=c.video.kind==='demo';document.querySelector('#stage').innerHTML=`<section class="card video-card"><div class="row"><h2>교육 영상</h2><span class="badge">${demo?'가상 영상 · 30초':'교육 영상'}</span></div><p class="muted">${esc(c.description)}</p>${demo?`<div class="video"><small>한솔홀딩스 안전관리</small><div class="symbol">◈</div><h2>${esc(c.title)}</h2><span>실제 영상이 들어갈 시연 공간입니다.</span></div><div class="bar"><button class="btn" id="play">▶ 재생</button><div class="track"><div class="fill" style="width:${Math.min(100,p.watched/30*100)}%"></div></div><span id="time">${Math.floor(p.watched)} / 30초</span></div>`:'<video id="actualVideo" class="media-player" controls playsinline preload="metadata" controlslist="nodownload noplaybackrate"></video>'}<p id="hint" class="muted">${T.watched(p)?'영상 시청 완료':'영상을 끝까지 시청하면 평가가 열립니다.'}</p></section><div class="note learning-rule">영상 전체 시청 후 <strong>10문항 중 8문항</strong>을 맞히면 시연 결과가 완료로 표시됩니다. 법정 이수 판정은 아닙니다.${demo?'<br>가상 영상과 예시 문제를 사용하는 시연입니다.':''}</div><div class="visitor-dock"><button id="start" class="btn m_primary primary wide" ${T.watched(p)?'':'disabled'}>10문항 평가 ${p.score!==null?'다시 풀기':'시작'} →</button></div>${p.score!==null?'<button id="result" class="btn wide">평가 결과 보기</button>':''}`;
 document.querySelector('#start').onclick=()=>{if(!T.watched(person()))return;screen='quiz';questionIndex=0;answers=Array(10).fill(null);render();window.scrollTo(0,0)};document.querySelector('#result')?.addEventListener('click',()=>{screen='result';render()});
 if(demo)document.querySelector('#play').onclick=()=>{if(timer){stop();return}const expected=stamp(person());let pos=person().watched>=30?0:person().watched;document.querySelector('#play').textContent='Ⅱ 일시정지';timer=setInterval(()=>{if(document.hidden){stop();return}try{pos=Math.min(30,pos+1);patchPerson(expected,p=>{p.watched=Math.max(p.watched,pos)});document.querySelector('.fill').style.width=pos/30*100+'%';document.querySelector('#time').textContent=pos+' / 30초';if(pos>=30){stop();unlock()}}catch(e){stop();notice(e.message,true)}},1000)};
 else loadVideo(c);
}
function unlock(){document.querySelector('#hint').textContent='영상 시청 완료 · 평가를 시작할 수 있습니다.';document.querySelector('#start').disabled=false}
async function source(v){if(v.kind==='url')return v.url;const blob=await VideoStore.get(v.assetId);if(!blob)throw Error('저장된 영상 파일이 없습니다. 저장한 브라우저에서 열거나 관리자에게 문의해주세요.');const u=URL.createObjectURL(blob);objectURLs.push(u);return u}
async function loadVideo(c){const generation=epoch,expected=stamp(person()),el=document.querySelector('#actualVideo');try{const src=await source(c.video);if(generation!==epoch)return;el.src=src;let max=person().watched,lastWrite=0;
 el.onloadedmetadata=()=>{try{if(!Number.isFinite(el.duration)||el.duration<=0)throw Error('영상 길이를 확인할 수 없습니다. 다른 영상 파일을 사용해주세요.');patchPerson(expected,p=>{p.duration=el.duration});if(!T.watched(person()))el.currentTime=Math.min(max,el.duration);else unlock()}catch(e){notice(e.message,true)}};
 el.onseeking=()=>{if(el.currentTime>max+.4)el.currentTime=max};
 el.onratechange=()=>{if(el.playbackRate!==1)el.playbackRate=1};
 el.ontimeupdate=()=>{if(el.seeking||el.currentTime>max+1.5)return;max=Math.max(max,el.currentTime);if(max-lastWrite>=1){lastWrite=max;try{patchPerson(expected,p=>p.watched=Math.max(p.watched,max))}catch(e){el.pause();notice(e.message,true)}}};
 el.onended=()=>{if(max>=el.duration-1.5)try{patchPerson(expected,p=>{p.duration=el.duration;p.watched=el.duration});unlock()}catch(e){notice(e.message,true)}};
 el.onerror=()=>notice('영상을 재생할 수 없습니다. 주소 접근 권한 또는 파일 형식을 확인해주세요.',true);
 }catch(e){notice(e.message,true)}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
function quiz(){const p=person(),c=course(p),expected=stamp(p),i=questionIndex,q=c.questions[i];
 document.querySelector('#stage').innerHTML=`<section class="card quiz-card"><div class="quiz-count"><strong>문제 ${i+1}<span> / 10</span></strong><span id="answeredCount">${answers.filter(a=>a!==null).length}개 답변</span></div><progress class="quiz-progress" max="10" value="${i+1}" aria-label="현재 문제"></progress><form id="quiz"><fieldset><legend id="questionTitle" tabindex="-1">${esc(q[0])}</legend>${q[1].map((v,j)=>`<label class="answer-option"><input type="radio" name="q${i}" value="${j}" ${answers[i]===j?'checked':''} required><span>${esc(v)}</span></label>`).join('')}</fieldset><p class="answer-hint">정답이라고 생각하는 보기 하나를 선택하세요.</p><div class="visitor-dock quiz-dock"><button class="btn" type="button" id="prevQuestion" ${i===0?'disabled':''}>이전</button><button class="btn m_primary primary" id="nextQuestion" ${answers[i]===null?'disabled':''}>${i===9?'답안 제출하기':'다음 문제 →'}</button></div></form></section><button class="btn text-button" id="back">← 영상 다시 보기</button>`;
 document.querySelector('#quiz').onchange=e=>{answers[i]=Number(e.target.value);document.querySelector('#nextQuestion').disabled=false;document.querySelector('#answeredCount').textContent=answers.filter(a=>a!==null).length+'개 답변'};
 document.querySelector('#prevQuestion').onclick=()=>{questionIndex--;quiz();focusQuestion()};
 document.querySelector('#quiz').onsubmit=e=>{e.preventDefault();if(answers[i]===null)return;if(i<9){questionIndex++;quiz();focusQuestion();return}attempt(()=>{const score=T.score(answers,c.questions);patchPerson(expected,p=>{if(!T.watched(p))throw Error('영상 전체 시청이 필요합니다.');p.score=score;p.answers=[...answers];p.attempts++;p.completedAt=T.complete(p)?new Date().toISOString():null});screen='result';render();window.scrollTo(0,0)})};
 document.querySelector('#back').onclick=()=>{screen='video';render();window.scrollTo(0,0)};
}
function focusQuestion(){document.querySelector('#questionTitle')?.focus({preventScroll:true});document.querySelector('.quiz-card')?.scrollIntoView({block:'start'})}
function result(){const p=person(),c=course(p);document.querySelector('#stage').innerHTML=`<section class="card result-card"><div class="result-icon ${T.complete(p)?'passed':'retry'}" aria-hidden="true">${T.complete(p)?'✓':'↻'}</div>${badge(p)}<h2 style="margin-top:18px">${T.complete(p)?'사전 안전교육을 완료했습니다.':'8문항 이상 정답이 필요합니다.'}</h2><p>${esc(c.title)} · v${c.revision}</p><div class="result">${p.score}<small> / 10문항 정답</small></div><div class="note">이 결과는 배정된 영상과 문제 버전에 연결됩니다.<br>같은 브라우저의 관리자 화면에서 확인할 수 있습니다. 본인확인 및 법정 이수 증빙과는 연결되지 않습니다.</div>${p.answers?`<details><summary>문항별 정답 확인</summary>${c.questions.map((q,i)=>`<p><b>${i+1}. ${p.answers[i]===q[2]?'정답':'오답'}</b><br>${esc(q[0])}<br>정답: ${esc(q[1][q[2]])}</p>`).join('')}</details>`:''}<div class="actions result-actions"><button id="again" class="btn ${T.complete(p)?'':'m_primary primary'}">다시 풀기</button><button class="btn" id="back">영상 보기</button></div></section>`;document.querySelector('#again').onclick=()=>{answers=Array(10).fill(null);questionIndex=0;screen='quiz';render()};document.querySelector('#back').onclick=()=>{screen='video';render()}}
function renderAdmin(){app.innerHTML=`<nav class="p_tabs" aria-label="교육 관리 화면"><button class="btn" type="button" data-tab="people" aria-pressed="${tab==='people'}">교육 현황</button><button class="btn" type="button" data-tab="peak" aria-pressed="${tab==='peak'}">집중 방문일 예시</button><button class="btn" type="button" data-tab="templates" aria-pressed="${tab==='templates'}">교육 템플릿</button></nav><div id="message" role="status" aria-live="polite"></div><div id="adminStage"></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(dirty&&!confirm('저장하지 않은 편집 내용이 있습니다. 이동하시겠습니까?'))return;editing=null;dirty=false;tab=b.dataset.tab;render()});if(editing)editor();else if(tab==='templates')library();else if(tab==='peak')peakDay();else dashboard()}
function library(){document.querySelector('#adminStage').innerHTML=`<div class="note">영상 + 문제 10개 + 정답을 하나의 템플릿으로 저장합니다. 게시본은 수정되지 않고 새 버전으로 쌓입니다. 영상 파일은 이 브라우저에 보관됩니다.</div><div class="actions"><button class="btn m_primary primary" id="newTemplate">+ 새 교육 템플릿</button></div><div class="template-grid" style="margin-top:20px">${state.templates.map(t=>`<article class="card template-card"><div class="template-cover"><b>▷</b><span>${t.draft.video.kind==='demo'?'가상 영상':t.draft.video.kind==='file'?'저장된 영상 파일':'영상 주소'}<br>10문항 평가 포함</span></div><h2>${esc(t.draft.title||'제목 없는 초안')}</h2><p class="muted">${esc(t.draft.description)}</p><span class="badge">${t.versions.length?'게시본 v'+t.versions.length+' · 편집 초안 보유':'초안 · 미게시'}</span><div class="actions"><button data-edit="${esc(t.id)}" class="btn m_primary primary">영상·문제 편집</button><button class="btn" data-copy-template="${esc(t.id)}">복사해 재사용</button></div>${t.versions.length?`<details class="history"><summary>게시 이력 ${t.versions.length}개</summary>${t.versions.slice().reverse().map(v=>`<p><b>v${v.revision} · ${esc(v.title)}</b><br><small>${esc(formatDate(v.publishedAt))}</small><br><button class="btn m_small compact" data-reuse="${esc(t.id)}:${v.revision}">이 게시본을 새 템플릿으로</button></p>`).join('')}</details>`:''}</article>`).join('')}</div>`;
document.querySelector('#newTemplate').onclick=()=>{editing={id:uid(),draft:{title:'',description:'',video:{kind:'demo'},questions:Array.from({length:10},()=>['',['','',''],0])},versions:[]};dirty=false;render()};document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=T.clone(template(b.dataset.edit));dirty=false;render()});document.querySelectorAll('[data-copy-template]').forEach(b=>b.onclick=()=>copyTemplate(template(b.dataset.copyTemplate).draft));document.querySelectorAll('[data-reuse]').forEach(b=>b.onclick=()=>{const [id,v]=b.dataset.reuse.split(':');copyTemplate(template(id).versions.find(x=>x.revision===Number(v)))})}
function copyTemplate(c){editing={id:uid(),draft:{title:c.title+' (복사)',description:c.description,video:T.clone(c.video),questions:T.clone(c.questions)},versions:[]};dirty=true;render()}
function formatDate(s){return Number.isNaN(Date.parse(s))?s:new Date(s).toLocaleString('ko-KR')}
function editor(){const c=editing.draft;document.querySelector('#adminStage').innerHTML=`<form id="editor" class="editor"><section class="card"><h2>1. 영상과 교육 정보</h2><label class="field">교육 제목<input class="input_text" id="title" maxlength="100" value="${esc(c.title)}" placeholder="예: 안전모·안전화 착용 교육"></label><label class="field">변경 사항·교육 안내<textarea class="input_text m_textarea" id="description" maxlength="1000">${esc(c.description)}</textarea></label><label class="field">영상 등록 방식<select class="input_text" id="kind">${[['demo','가상 영상 (30초 시연)'],['file','영상 파일 저장'],['url','영상 파일 주소 등록']].map(([v,s])=>`<option value="${v}" ${c.video.kind===v?'selected':''}>${s}</option>`).join('')}</select></label><div id="videoFields"></div><button class="btn" id="previewVideo" type="button">영상 미리보기</button></section><section class="card"><h2>2. 이 영상의 평가 문제</h2><p class="muted">각 문제의 보기 3개를 작성하고 정답을 선택하세요. 총 10문항 · 8문항 이상은 시연 설정입니다.</p>${c.questions.map((q,i)=>`<div class="question-edit"><label class="field"><strong>문제 ${i+1}</strong><textarea class="input_text m_textarea" data-question="${i}" maxlength="500">${esc(q[0])}</textarea></label>${q[1].map((s,j)=>`<div class="option"><input type="radio" name="answer${i}" data-answer="${i}" value="${j}" ${q[2]===j?'checked':''} aria-label="문제 ${i+1} 보기 ${j+1}을 정답으로"><input class="input_text" data-option="${i}:${j}" maxlength="300" value="${esc(s)}" aria-label="문제 ${i+1} 보기 ${j+1}" placeholder="보기 ${j+1}"></div>`).join('')}<small>선택한 원형 버튼이 정답입니다.</small></div>`).join('')}</section><p class="note">게시하면 새로운 버전이 만들어집니다. 기존 배정·이수 기록은 그대로 유지됩니다. 새 게시본은 ‘교육 현황’에서 선택해 배정하세요.</p><div id="editorMessage" role="status"></div><div class="sticky-actions"><button class="btn" type="submit">초안 저장</button><button type="button" class="btn m_primary primary" id="publish">저장하고 새 버전 게시</button><button class="btn" type="button" id="cancel">목록으로</button></div></form>`;
 videoFields();document.querySelector('#editor').oninput=e=>{dirty=true;const el=e.target;if(el.id==='title')c.title=el.value;else if(el.id==='description')c.description=el.value;else if(el.dataset.question!==undefined)c.questions[+el.dataset.question][0]=el.value;else if(el.dataset.option){const [i,j]=el.dataset.option.split(':').map(Number);c.questions[i][1][j]=el.value}else if(el.dataset.answer!==undefined)c.questions[+el.dataset.answer][2]=+el.value;else if(el.id==='videoUrl')c.video.url=el.value};document.querySelector('#kind').onchange=e=>{dirty=true;c.video={kind:e.target.value};videoFields()};document.querySelector('#editor').onsubmit=e=>{e.preventDefault();saveTemplate(false)};document.querySelector('#publish').onclick=()=>saveTemplate(true);document.querySelector('#cancel').onclick=()=>{if(dirty&&!confirm('저장하지 않은 편집 내용이 있습니다. 목록으로 이동하시겠습니까?'))return;editing=null;dirty=false;render()};document.querySelector('#previewVideo').onclick=()=>preview(c)}
function videoFields(){const v=editing.draft.video;document.querySelector('#videoFields').innerHTML=v.kind==='file'?`<label class="field">영상 파일 <input type="file" id="file" accept="video/mp4,video/webm,video/ogg"><small>권장 MP4 · 최대 150MB · 이 브라우저에 저장</small></label><p id="fileStatus">${v.assetId?'저장된 파일: '+esc(v.name):'아직 저장한 파일이 없습니다.'}</p>`:v.kind==='url'?`<label class="field">영상 파일 주소<input class="input_text" type="url" id="videoUrl" value="${esc(v.url||'')}" placeholder="https://example.com/safety.mp4"><small>브라우저에서 직접 재생 가능한 HTTPS 주소. YouTube 등의 페이지 주소는 지원하지 않습니다.</small></label>`:'<p class="muted">실제 영상 준비 전 30초 가상 영상으로 시연합니다.</p>';
 document.querySelector('#file')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;const target=editing;uploading=true;document.querySelector('#kind').disabled=true;document.querySelector('#publish').disabled=true;document.querySelector('#fileStatus').textContent='영상 저장 중…';try{const assetId=await VideoStore.put(f);if(editing!==target)return;editing.draft.video={kind:'file',assetId,name:f.name};dirty=true;document.querySelector('#fileStatus').textContent='저장된 파일: '+f.name}catch(err){if(editing===target)document.querySelector('#fileStatus').textContent=err.message}finally{uploading=false;if(editing===target){document.querySelector('#publish').disabled=false;document.querySelector('#kind').disabled=false}}})}
async function saveTemplate(post){const out=document.querySelector('#editorMessage');try{if(uploading)throw Error('영상 저장이 끝난 후 저장·게시해주세요.');if(post){T.valid(editing.draft);if(editing.draft.video.kind==='file'&&!await VideoStore.get(editing.draft.video.assetId))throw Error('영상 파일을 다시 저장해주세요.')}const edit=T.clone(editing);change(s=>{let t=s.templates.find(x=>x.id===edit.id);if(!t){t={id:edit.id,draft:edit.draft,versions:[]};s.templates.push(t)}else t.draft=edit.draft;if(post)T.publish(t,new Date().toISOString())});editing=T.clone(template(edit.id));dirty=false;render();notice(post?'새 버전을 게시했습니다. 교육 현황에서 방문자에게 배정할 수 있습니다.':'초안을 저장했습니다. 아직 방문자에게 배정할 수 없는 수정 사항은 게시 후 적용됩니다.')}catch(e){out.textContent=e.message;out.className='error'}}
async function preview(c){document.querySelector('#previewDialog')?.remove();const d=document.createElement('dialog');d.id='previewDialog';d.className='p_preview_dialog';d.innerHTML=`<div class="row"><h2>${esc(c.title||'영상 미리보기')}</h2><button class="btn" id="closePreview" aria-label="미리보기 닫기">닫기</button></div><div id="previewBody"></div>`;document.querySelector('.page_education').append(d);d.showModal();d.querySelector('#closePreview').onclick=()=>d.close();d.onclose=()=>{d.querySelector('video')?.pause();d.remove()};if(c.video.kind==='demo'){d.querySelector('#previewBody').innerHTML='<div class="video"><div class="symbol">▷</div><h2>30초 가상 영상</h2><p>방문자 화면에서 재생되는 시연 공간입니다.</p></div>';return}try{if(c.video.kind==='url'&&!/^https:\/\//.test(c.video.url||''))throw Error('HTTPS 영상 주소를 입력해주세요.');const src=await source(c.video);if(!d.isConnected)return;const v=document.createElement('video');v.controls=true;v.playsInline=true;v.className='media-player';v.src=src;v.onerror=()=>{const p=document.createElement('p');p.textContent='영상을 재생할 수 없습니다. 주소 또는 형식을 확인해주세요.';d.querySelector('#previewBody').append(p)};d.querySelector('#previewBody').append(v)}catch(e){if(d.isConnected)d.querySelector('#previewBody').textContent=e.message}}
function dashboard(){
 const counts=[['교육 대상',state.people.length],['교육 완료',state.people.filter(T.complete).length],['영상 시청 필요',state.people.filter(p=>!T.watched(p)).length],['평가·재응시 필요',state.people.filter(p=>T.watched(p)&&!T.complete(p)).length]];
 document.querySelector('#adminStage').innerHTML=`<div class="p_grid"><section class="card p_search"><h2>교육 대상 검색</h2><p class="p_help">대상을 선택하면 교육 이력과 개인 링크를 확인할 수 있습니다.</p><label class="p_label" for="search">이름 또는 업체</label><div class="p_search_control"><input class="input_text" id="search" type="search" placeholder="이름 또는 업체 검색" value="${esc(query)}"><button class="btn" id="resetFilters" type="button">초기화</button></div><label class="p_label" for="filter">진행 상태</label><select class="input_text p_filter" id="filter"><option value="">전체 상태</option>${['교육 완료','영상 시청 필요','평가 대기','재응시 필요'].map(s=>`<option ${filter===s?'selected':''}>${s}</option>`).join('')}</select><div class="p_summary"><h3>교육 대상 현황</h3><p>배정된 작업자의 교육 진행 현황</p><div class="p_counts">${counts.map(([label,n])=>`<span>${label} <strong>${n}</strong></span>`).join('')}</div></div><section class="p_register"><details><summary>방문자 등록과 교육 배정</summary><form id="add"><label class="field">작업자 이름<input class="input_text" name="name" maxlength="30" required></label><label class="field">소속 업체<input class="input_text" name="company" maxlength="60" required></label><label class="field">게시된 교육<select class="input_text" name="course">${options('common:1')}</select></label><button class="btn m_primary primary">방문자 등록</button></form></details></section><div class="p_list_head"><h3>교육 대상 목록</h3><select class="input_text" id="sort" aria-label="목록 정렬">${[['name','이름순'],['company','업체순'],['recent','최근 등록순']].map(([v,l])=>`<option value="${v}" ${sort===v?'selected':''}>${l}</option>`).join('')}</select></div><div id="people"></div></section><section class="card p_detail" id="educationDetail" aria-label="선택한 작업자 교육 상세"></section></div>`;
 list();
 document.querySelector('#search').oninput=e=>{query=e.target.value;page=1;expandedId=null;list()};
 document.querySelector('#filter').onchange=e=>{filter=e.target.value;page=1;expandedId=null;list()};
 document.querySelector('#sort').onchange=e=>{sort=e.target.value;page=1;expandedId=null;list()};
 document.querySelector('#resetFilters').onclick=()=>{query='';filter='';sort='name';page=1;expandedId=null;dashboard()};
 document.querySelector('#add').onsubmit=e=>{e.preventDefault();attempt(()=>{const f=new FormData(e.target),name=f.get('name').trim(),company=f.get('company').trim();if(!name||!company)throw Error('이름과 업체를 입력해주세요.');const [tid,rev]=f.get('course').split(':');let id;change(s=>{const p={id:uid(),name,company,history:[]};T.assign(p,s.templates.find(t=>t.id===tid),Number(rev));s.people.push(p);id=p.id});query='';filter='';page=1;expandedId=id;render();notice('방문자를 등록하고 교육을 배정했습니다.')})};
}
function peakDay(){
 document.querySelector('#adminStage').innerHTML=`<div class="p_peak"><header class="card p_peak_intro"><div><span class="badge m_brand">가상 시나리오</span><h2>100명 이상이 방문하는 아침</h2><p>방문 전에 교육을 마친 인원과 현장에서 교육 확인이 필요한 인원을 살펴보세요.</p></div><div class="p_peak_baseline"><span>현업에서 확인한 기존 상황</span><strong>100명 이상 집중 시 약 1시간 지체</strong><small>현장 사전교육에 인원이 몰린 경우 · 일자별 측정값은 아직 없음</small></div></header><div class="p_peak_grid"><section class="card p_peak_control"><h3>방문 규모 설정</h3><p class="p_help">아래 인원은 화면 시연용 가정입니다. 실제 명단·교육 기록은 바뀌지 않습니다.</p><label class="field" for="peakTotal">방문 예정 인원<select class="input_text" id="peakTotal">${[100,120,150,200].map(n=>`<option value="${n}" ${peakTotal===n?'selected':''}>${n}명</option>`).join('')}</select></label><label class="field" for="peakComplete">방문 전 교육 완료 인원<input class="input_text" id="peakComplete" type="number" min="0" max="${peakTotal}" step="1" value="${peakComplete}"></label><p id="peakInputHelp" class="p_help">완료 인원을 바꾸면 현장 확인 대상이 함께 바뀝니다.</p></section><section class="card p_peak_outcome"><div class="p_peak_heading"><div><h3>방문 당일 교육 준비 현황</h3><p>방문 전 완료 여부에 따라 현장 확인 대상을 나눈 예시입니다.</p></div><span class="badge">시뮬레이션</span></div><dl class="p_peak_metrics"><div><dt>방문 예정</dt><dd id="peakTotalValue"></dd></div><div><dt>방문 전 완료</dt><dd id="peakCompleteValue"></dd></div><div><dt>현장 확인 대상</dt><dd id="peakPendingValue"></dd></div></dl><div class="p_peak_bar" role="img" id="peakBar" aria-label="방문 전 교육 완료와 현장 확인 대상 비율"><span id="peakBarDone"></span><span id="peakBarPending"></span></div><div class="p_peak_legend"><span><i class="p_peak_dot m_done"></i>방문 전 완료 <strong id="peakRate"></strong></span><span><i class="p_peak_dot m_pending"></i>현장 확인 필요</span></div><div class="p_peak_actions"><h4>현장에서 확인할 일</h4><ol><li>교육 완료자의 기록과 대상자 확인</li><li>미완료자에게 교육·평가 안내</li><li>당일 현장 특이사항 별도 안내</li></ol></div></section></div><section class="card p_peak_compare"><div><h3>지체시간 비교</h3><p>현재는 기존 사례만 확인됐습니다. 사전교육 도입 후 시간은 현장 측정으로 검증해야 합니다.</p></div><div class="p_peak_times"><div><span>기존 · 100명 이상 집중일</span><strong>약 1시간 지체</strong><small>현업 확인</small></div><div><span>방문 전 교육 적용 후</span><strong>측정 전</strong><small>교육 완료 확인과 당일 안내 시간은 현장에 남음</small></div></div></section></div>`;
 const total=document.querySelector('#peakTotal'),complete=document.querySelector('#peakComplete');
 const update=(commit=false)=>{peakTotal=Number(total.value);peakComplete=Math.max(0,Math.min(peakTotal,Number(complete.value)||0));complete.max=peakTotal;if(commit)complete.value=peakComplete;const pending=peakTotal-peakComplete,rate=Math.round(peakComplete/peakTotal*100);document.querySelector('#peakTotalValue').textContent=peakTotal+'명';document.querySelector('#peakCompleteValue').textContent=peakComplete+'명';document.querySelector('#peakPendingValue').textContent=pending+'명';document.querySelector('#peakRate').textContent=rate+'%';document.querySelector('#peakBarDone').style.width=rate+'%';document.querySelector('#peakBarPending').style.width=(100-rate)+'%';document.querySelector('#peakBar').setAttribute('aria-label',`방문 전 교육 완료 ${peakComplete}명, 현장 확인 필요 ${pending}명`)};
 total.onchange=()=>update(true);complete.oninput=()=>{if(complete.value!=='')update()};complete.onchange=()=>update(true);update(true);
}
function list(){
 const q=query.trim().toLocaleLowerCase('ko-KR');
 const items=state.people.filter(p=>(!filter||T.status(p)===filter)&&(`${p.name} ${p.company}`).toLocaleLowerCase('ko-KR').includes(q));
 if(sort==='recent')items.reverse();else items.sort((a,b)=>(sort==='company'?a.company.localeCompare(b.company,'ko'):0)||a.name.localeCompare(b.name,'ko',{numeric:true}));
 const pages=Math.max(1,Math.ceil(items.length/pageSize));page=Math.min(page,pages);
 const offset=(page-1)*pageSize,visible=items.slice(offset,offset+pageSize);
 if(!visible.some(p=>p.id===expandedId))expandedId=visible[0]?.id||null;
 document.querySelector('#people').innerHTML=`<div class="p_list_toolbar"><p id="resultCount" role="status" aria-live="polite">${filter?esc(filter):'전체'} <strong>${items.length}명</strong></p><label class="page-size">페이지당 <select class="input_text" id="pageSize" aria-label="페이지당 표시 인원">${[25,50,100].map(n=>`<option value="${n}" ${pageSize===n?'selected':''}>${n}명</option>`).join('')}</select></label></div><ul class="p_results">${visible.map(p=>`<li data-person="${esc(p.id)}"><button class="result_card" type="button" data-detail="${esc(p.id)}" aria-pressed="${expandedId===p.id}" aria-controls="educationDetail"><span class="i_top"><span class="i_name">${esc(p.name)}</span>${badge(p)}</span><span class="i_meta">${esc(p.company)} · ${esc(course(p)?.title||'교육 미배정')} · v${p.revision}</span></button></li>`).join('')}</ul>${visible.length?'':'<p class="p_no_results">조건에 맞는 방문자가 없습니다. 검색어 또는 상태를 변경해주세요.</p>'}<div class="pagination"><span class="muted">${items.length?offset+1:0}–${Math.min(offset+pageSize,items.length)} / ${items.length}명</span><nav aria-label="방문자 목록 페이지"><button class="btn" id="prevPage" ${page===1?'disabled':''} aria-label="이전 페이지">← 이전</button><span>${page} / ${pages}</span><button class="btn" id="nextPage" ${page===pages?'disabled':''} aria-label="다음 페이지">다음 →</button></nav></div>`;
 const p=visible.find(item=>item.id===expandedId);
 const detail=document.querySelector('#educationDetail');
 detail.innerHTML=p?`<div class="visitor-detail"><div class="p_worker_head"><span class="p_avatar" aria-hidden="true">${esc(p.name.slice(0,1))}</span><div class="p_identity"><h2>${esc(p.name)}</h2><p>${esc(p.company)}</p></div>${badge(p)}</div><div class="p_body"><dl class="p_metrics"><div class="p_metric"><dt>배정 교육</dt><dd>${esc(course(p)?.title||'미배정')} <small>v${p.revision}</small></dd></div><div class="p_metric"><dt>영상 시청</dt><dd>${p.duration?Math.min(100,Math.floor(p.watched/p.duration*100)):0}%</dd></div><div class="p_metric"><dt>평가 결과</dt><dd>${p.score===null?'미응시':p.score+' / 10'}</dd></div><div class="p_metric"><dt>응시 횟수</dt><dd>응시 ${p.attempts}회</dd></div></dl><section class="p_detail_section"><div class="p_section_head"><h3>방문 전 교육 안내</h3><p>개인 링크로 배정된 영상과 평가를 확인합니다.</p></div><p class="p_completion">${p.completedAt?'교육 완료 · '+esc(formatDate(p.completedAt)):'교육 완료 전'}</p><div class="actions"><a class="btn m_primary button primary" href="${esc(url(p))}" target="_blank" rel="noopener">방문자 화면 ↗</a><button class="btn" data-copy="${esc(p.id)}">개인 링크 복사</button></div></section><details class="history p_detail_section"><summary>교육 변경·이전 기록</summary><label class="field">배정할 교육<select class="input_text" data-assignment="${esc(p.id)}">${options(stamp(p))}</select></label><button class="btn" data-assign="${esc(p.id)}">선택한 교육으로 배정</button><p class="muted">변경 시 현재 기록을 보존하고 새 교육을 처음부터 시작합니다.</p>${(p.history||[]).map(h=>`<p class="p_history_item">${esc(course(h)?.title||'교육')} · v${h.revision}<br>${esc(T.status(h))} · ${h.score===null?'미응시':h.score+'/10 정답'}${h.completedAt?' · '+esc(formatDate(h.completedAt)):''}</p>`).join('')}</details></div></div>`:`<div class="p_empty"><h2>교육 대상을 선택해 주세요</h2><p>${items.length?'목록에서 작업자를 선택하면 교육 결과가 표시됩니다.':'현재 조건에 맞는 작업자가 없습니다.'}</p></div>`;
 document.querySelector('#pageSize').onchange=e=>{pageSize=+e.target.value;page=1;expandedId=null;list()};
 const move=delta=>{page+=delta;expandedId=null;list();document.querySelector('#resultCount').scrollIntoView({block:'nearest'})};
 document.querySelector('#prevPage').onclick=()=>move(-1);document.querySelector('#nextPage').onclick=()=>move(1);
 document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{expandedId=b.dataset.detail;list();document.querySelector(`[data-detail="${expandedId}"]`)?.focus()});
 detail.querySelector('[data-copy]')?.addEventListener('click',async e=>{const u=url(state.people.find(person=>person.id===e.currentTarget.dataset.copy));try{await navigator.clipboard.writeText(u);notice('개인별 교육 링크를 복사했습니다.')}catch{notice('복사할 링크: '+u)}});
 detail.querySelector('[data-assign]')?.addEventListener('click',e=>attempt(()=>{const id=e.currentTarget.dataset.assign,val=detail.querySelector('[data-assignment]').value,[tid,rev]=val.split(':');const current=state.people.find(person=>person.id===id);if(stamp(current)===val){notice('이미 배정된 교육입니다.');return}if(!confirm('기존 기록은 보존되고 새 교육을 처음부터 시작합니다. 배정하시겠습니까?'))return;change(s=>T.assign(s.people.find(person=>person.id===id),s.templates.find(t=>t.id===tid),Number(rev)));render();notice('교육을 변경했습니다. 이전 기록은 개인 상세에서 확인할 수 있습니다.')}));
}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
window.addEventListener('storage',e=>{if(e.key!==key)return;try{const before=person()&&stamp(person());state=read()||state;if(admin){if(!editing)render()}else if(person()&&before!==stamp(person())){screen='video';render();notice('관리자가 교육을 변경했습니다. 새로 배정된 교육을 확인해주세요.')}else if(!timer&&screen==='video')render()}catch{}});
render();
})();
